[package]
name = "json_ellipsis"
version = "0.1.0"
authors = ["KoharaKazuya <reflect.results@gmail.com>"]
edition = "2018"

[dependencies]
either = "1.5.3"
indexmap = "1.3.0"
serde_json = { version = "1.0.41", features = ["preserve_order"] }
