[package]
name = "json_ellipsis_web"
version = "0.1.0"
authors = ["KoharaKazuya <reflect.results@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
json_ellipsis = { path = "../core" }
wasm-bindgen = "0.2.52"
